"""Lazy, non-blocking 古书定调 segment for chat system prompts.

The redesigned 古书定调 (PersonaQuote + VerdictQuote) is generated by
``classics_polisher.polish_classics_for_chart`` and cached under
``chart_cache (kind='classics', key='v2')``. This module reads that cache
on the chat send path and formats the cached payload into a plaintext
segment that gets appended to the LLM system prompt.

Hard rules:
* Cache miss → return empty string. **Never block** the chat send.
* Cache hit but persona is null → return empty string. A bare verdict line
  without context is more confusing than helpful.
* Always include the 围栏 line: "仅作风格引证，事实仍以前述【结构事实表】为准".
"""
from __future__ import annotations

import json
import logging
from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.chart import ChartCache

logger = logging.getLogger(__name__)

# 单一真理源在 classics_polisher — writer (charts.py API) 与 reader (本模块)
# 都从那儿引，防止 schema bump 时一头改一头忘的 silent drift。
from app.services.classics_polisher import CLASSICS_CACHE_VERSION as _CLASSICS_CACHE_VERSION


def _format_segment(
    persona: dict[str, Any] | None, verdict: dict[str, Any] | None,
) -> str:
    if not persona:
        return ""
    book = persona.get("book") or ""
    chapter = persona.get("chapter") or ""
    quote = persona.get("quote") or ""
    plain = persona.get("plain") or ""

    lines = [
        "[古书定调 — 仅作风格引证，事实仍以前述【结构事实表】为准]",
        "",
        f"古人画像（{book}·{chapter}）：",
        quote,
        f"（白话：{plain}）",
    ]
    if verdict:
        v_book = verdict.get("book") or ""
        v_chapter = verdict.get("chapter") or ""
        v_quote = verdict.get("quote") or ""
        lines.append("")
        lines.append(f"古人定语（{v_book}·{v_chapter}）：{v_quote}")
    return "\n".join(lines)


async def maybe_classics_segment(
    db: AsyncSession, chart_id: UUID,
) -> str:
    """Read cache (no LLM, no retrieval) and format a segment if available.

    Returns "" on cache miss / corruption / persona missing — chat must
    keep working. Logs at warning level on JSON corruption."""
    try:
        row = (await db.execute(
            select(ChartCache).where(
                ChartCache.chart_id == chart_id,
                ChartCache.kind == "classics",
                ChartCache.key == _CLASSICS_CACHE_VERSION,
            )
        )).scalar_one_or_none()
    except Exception as exc:  # noqa: BLE001 — defensive against any DB hiccup
        logger.warning("classics cache read failed: %r", exc)
        return ""

    if not row or not row.content:
        return ""
    try:
        data = json.loads(row.content)
    except (ValueError, TypeError) as exc:
        logger.warning("classics cache JSON corrupt: %r", exc)
        return ""

    return _format_segment(data.get("persona"), data.get("verdict"))


__all__ = ["maybe_classics_segment"]
